"""Compatibility facade for CLI default values."""

from __future__ import annotations

from app.config.cli import (
    DEFAULT_API_CSV,
    DEFAULT_BLOCKED_STOP_THRESHOLD,
    DEFAULT_BROWSER_ACTIVITY_TTL_SECONDS,
    DEFAULT_BROWSER_SESSION_JSON,
    DEFAULT_BROWSER_TTL_SECONDS,
    DEFAULT_BROWSER_WAIT_MS,
    DEFAULT_DATABASE,
    DEFAULT_MAX_RETRIES,
    DEFAULT_REQUEST_DELAY_SECONDS,
    DEFAULT_RETRY_BACKOFF_SECONDS,
    DEFAULT_SCRAPE_CHECKPOINT_JSON,
    DEFAULT_SCRAPE_OUTPUT_CSV,
    DEFAULT_SCRAPE_REPORT_JSON,
)


# ============================================================================
# PUBLIC RE-EXPORTS
# ============================================================================
__all__ = [
    "DEFAULT_API_CSV",
    "DEFAULT_BLOCKED_STOP_THRESHOLD",
    "DEFAULT_BROWSER_ACTIVITY_TTL_SECONDS",
    "DEFAULT_BROWSER_SESSION_JSON",
    "DEFAULT_BROWSER_TTL_SECONDS",
    "DEFAULT_BROWSER_WAIT_MS",
    "DEFAULT_DATABASE",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_REQUEST_DELAY_SECONDS",
    "DEFAULT_RETRY_BACKOFF_SECONDS",
    "DEFAULT_SCRAPE_CHECKPOINT_JSON",
    "DEFAULT_SCRAPE_OUTPUT_CSV",
    "DEFAULT_SCRAPE_REPORT_JSON",
]
